// <auto-generated />
namespace DiplomaDataModel.Migrations.Diploma
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class uniqueStudentChoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uniqueStudentChoice));
        
        string IMigrationMetadata.Id
        {
            get { return "201510162105093_uniqueStudentChoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
